### ISSUE TITLE
Stuck on loading

### ISSUE THREAD

**Issue by dimitarnestorov** [Leocardoso94/Free-Courses#149]
![image](https://user-images.githubusercontent.com/8790386/67316699-9b48cf00-f511-11e9-96fa-4f2e0f4ea953.png)

Whatever category I choose this the only thing I see

**Comment by Leocardoso94** [comment]
Thanks for sharing!

Fix on https://github.com/Leocardoso94/Free-Courses/commit/087804ce0f74d43c98f1334d4d0d05d02041fe40
