### ISSUE TITLE
Roadmap will be useful

### ISSUE THREAD

**Issue by usmanakram1996** [Leocardoso94/Free-Courses#67]
I will recommend to embed a roadmap for web developers which will help a the community a lot in learning the required skills through your resources

**Comment by Leocardoso94** [comment]
I did not understand much about the idea, would you have any examples?

**Comment by usmanakram1996** [comment]
A proper path should be added that which courses leads to the respective skill set one wants to aim at and the learners could stick to their goals in this way

**Comment by Leocardoso94** [comment]
Hi @usmanakram1996 ,

The idea is interesting, but it avoids a bit of the idea of the project, which is to offer free courses.

But I'll think about it better, thank you.
