### ISSUE TITLE
Weekly newsletter section/category

### ISSUE THREAD

**Issue by bhaskarmac** [Leocardoso94/Free-Courses#77]
Hi @Leocardoso94 ,

I think we should add weekly newsletter category on the website like the other languages/frameworks have. This weekly newsletter would contain all possible weekly newsletter subscription sites like https://nodeweekly.com, etc. This will help users to learn from reading the newsletter and keep them stay updated.

Please let me know what is your view on this so that I will add the category and the possible weekly newsletter links.

**Comment by Leocardoso94** [comment]
H @bhaskarmac 

I loved the idea.

I'll leave you in charge, okay?

Any doubt you have can let me know.

Thanks!

**Comment by bhaskarmac** [comment]
@Leocardoso94 

Thank you for this. Yes, I will add the category and start adding the newsletter links :+1:  :)

**Comment by bhaskarmac** [comment]
Hi @Leocardoso94 

Added the category and first newsletter link. I will be adding many other links as I get time :) :fireworks:

**Comment by Leocardoso94** [comment]
#78
