### ISSUE TITLE
Adding New Courses

### ISSUE THREAD

**Issue by Leocardoso94** [Leocardoso94/Free-Courses#97]
### 🆕🐥☝ First Timers Only
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 [About First Timers Only](http://www.firsttimersonly.com/).

### 🎃💻👕 Hacktoberfest: Trick or Treat!
If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. Plus I’m sure we can teach you a cool trick or two in the process

### 🤔 What you will need to know
JSON, Node.js, JavaScript, CSS, React.

### :dart: The goal
Hi people,

I need to add more courses to the platform, in case you know of any programming course and want to help, please help me.

Check the [CONTRIBUTING.md](https://github.com/Leocardoso94/Free-Courses/blob/master/CONTRIBUTING.md) to get more informations.

You can see the project here: https://freecourses.github.io/

**Comment by anabellaspinelli** [comment]
Hello! 😊 I think this would be a great addition: 

https://egghead.io/lessons/javascript-introduction-to-github

It's a great course to get started with GitHub and open source. It really helped me figure out the confusing parts about contributing. 

Would it fall into the `Git` category or maybe a new one?

**Comment by Leocardoso94** [comment]
Hi @anabellaspinelli !!

Nice course! You can add it to the git category, it's great!

**Comment by anabellaspinelli** [comment]
There's also this one, about Redux by its creator... but there's no Redux category and no icon in Devicons!! 😱 Should I add it anyway?

**Comment by Leocardoso94** [comment]
Hmmm, you can add to React category.

In the future I need to see an alternative for the other icons
